### ISSUE TITLE
How to generate up to date fbtBlend.h and Blender.h (for version 2.80)

### ISSUE THREAD

**Issue by melMass** [Flix01/fbtBlend-Header-Only#1]
Hi,

Thanks for the open repo, I'm making a parser in Nim-lang for 2.8 and I would like to generate an up to date Blender types header. Can you share the process?

Thanks

**Comment by Flix01** [comment]
As far as I remember, you must compile the file [fbtBlendUpdater.cpp](https://github.com/Flix01/fbtBlend-Header-Only/blob/master/fbtBlendUpdater/fbtBlendUpdater.cpp) and then, if you run it without arguments, it should display the instructions.

**Comment by melMass** [comment]
Thanks I'll try that

**Comment by Flix01** [comment]
Did it work?

**Comment by Flix01** [comment]
Closing this. (You can reopen it if you like).
