### ISSUE TITLE
Compilation on arm64 processors

### ISSUE THREAD

**Issue by MaxiPaille** [Flix01/fbtBlend-Header-Only#6]
Hello,

First of all, thanks for your work. It will help me a lot.

I failed to compile the samples on my Macbook Pro M1.
Everything works fine with g++/clang except the FBT_ARCH detection part. I fixed the issue by adding `defined(__aarch64__)`.

**fbtBlend.h**
```
#if defined(__x86_64__)     || defined(_M_X64)      || \
    defined(__powerpc64__)  || defined(__alpha__)   || \
    defined(__ia64__)       || defined(__s390__)    || \
    defined(__s390x__)	    || defined(__aarch64__)
#define FBT_ARCH FBT_ARCH_64
#else
#define FBT_ARCH FBT_ARCH_32
#endif
```

As more and more OS are adopting arm64 support, I suggest you to add this changes in your code.
You should also add the build instructions for MacOs as it works perfectly using the linux command line.

Cheers

**Comment by Flix01** [comment]
Done. Thank you for you feedback!
